username: ENC[AES256_GCM,data:G9Qn87C7eg==,iv:OLMvL3nDC6RdRfcAB1ns8YRZjhrwKELmMv0c3eGc2Vc=,tag:ijBy7DZoOikzeh3asxxLuw==,type:str]
password: ENC[AES256_GCM,data:z48p3dAXth+iac+X,iv:kA/7YmYScK2sKsXFY8dV1DBxvvmfBaCPD6y6rAqrSvs=,tag:dQN8DYn73RbGHN/ryFeKeQ==,type:str]
sops:
  age:
    - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYnpKSDZZUWUzMCtNMHQ1
        V21uRkg5MnF6TEsxOW8rcUlEZTUzb0FWRG1NCktXQjAwcVhhTm01WjRSOThwdVI5
        ZkwrU2xpdUNCRVY0OGZoQ3dieFRiWE0KLS0tIDA0VzlKVFpyK2FZR09JZWxjSE1z
        NmZGYmtYOTg4QyttcjlpT3BVS0VQa0EKRftO8vqbYs7bgxDdbjHAna2DBdqdO+i+
        xUJEmag1KXJdct8rhQ59RFc3njwBGt/pnYNEJm8lRnXITK+sOawT4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-14T06:41:29Z"
  mac: ENC[AES256_GCM,data:TkSs3NqFX56Lljo1JNLt+698EApeBgYLjUuIl0KPp0Tci3lwrPBov61JX8hS19mt4O5Hhc5FaPagp4cqcMzWkaIw9yfBbCEuQqSNNOYeEGCKvQq8Y7DvlqGBS9mgy1dAeEtft8ohtwv/ItLdusJbYsoMWx/o7cRxIGifSsJSJ20=,iv:E5cmXVPPl8DwHuzGX/vXTB39A/zkIn/gAATEhbknqRw=,tag:2MJH1A6rFtjBrRawhCNl1A==,type:str]
  pgp:
    - created_at: "2026-05-14T06:41:29Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaAQ/+JhoRlUuVmGzBzafwwSgwMkspZWBWsA2xRKptOvpIb5ta
        8ugM7q5YEPbNF+bWr5k4+QfyNOYoM4OjkiPAtdrnr/Dzx7bQlf8X1Vc9xzTobfcn
        sog7QP8k0dQjiRVDfhSudgj3j4qkSn7mXhyUuiGvwDHKL462O9m48crpfn/u9ZCn
        lj1SFTM4BkKEgHQxfZ163dpMYDHCSY5EeSMTM2L0xY1JEEFlvBdSRoG2jZnFioRz
        hFUxngA59S8XWXkcJE885A49/ZrHNcUCDD/7wjZXfO1Bq1Ny9xzvPyGM4sde2T7f
        AEoBJ1bT2sv86KRbfRj27jiXqt5I4D3BsC9p8kKBSenL7fpOn8QzN55bFFqzLMRQ
        gBdt1jTQDlCNgW3dsnzhIvFrf5nMZlXo0gg3WwWBQwGMG+OUW4qjTWXFoHQD9W2h
        42hnMFa8bi6YUb1clBtyMnrsr/R1hehBk9DEp51Y6bNOZVjsROK9hLp9C9PsTZ32
        eBPU1oFXrliFGUV0GBC6AVi7ZIg5QvyUwJP0apTss374b0dQ/DAWznm1IyKoo5aR
        DttbYsvewXgMxDL5b3yb3Bn8Huqs01e3DOGvOVtFzz9KysTzexAZ/gTRQpRVd0ea
        W5EjdPojHSENuzxditMNBu1FfTOr45G5civouHYbI/06eDOB6rlc1RfR7aiTfw7S
        XAFCOisir2pfYRwMhPylcUQro4cg7Nkq917OAsmsWq/PTSGC+aIgxhcOAkdos430
        1A7FxFzVXonxZ6Qbb2KKlsqS+mj3OBELuVh2MOHeeySx1hufoPW7hr6HMvbB
        =FOF8
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  unencrypted_suffix: _unencrypted
  mac_only_encrypted: true
  version: 3.11.0
