username: ENC[AES256_GCM,data:ePDgEwK7NOTSMcN1Aw==,iv:TkJE2EskvdgyI4VufMH5QypLWv6SXMUY8kyrCQFZASQ=,tag:WBAizFZmopMpwPrRiuttoA==,type:str]
password: ENC[AES256_GCM,data:XfSn3YQaH5sVYj8ubew=,iv:koQX6N0veIQlNvdTvwvceMHU5cBpr2cQbuvjfzNoFiA=,tag:nxidYM3U0g4khQujvlsIPw==,type:str]
sops:
  age:
    - recipient: age1k9pgstv92fnq4mpupu2msd9j7zvv96l07ueqfckrv3nwq94t7vzq7typqx
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYbjhNQjZ6b0hSdjlsbDZz
        WGZnWktDTERIR21nVEE5MHpMOUNRaUl4UUM4Cmd1ZmVGSXBwMzBVNFlETUZVOVVp
        YkRraDBLZzdKTTRPLzNOVWZwcGxXOGMKLS0tIGwwNDQvMGx3TkJveEhPVkM5L29z
        akphUjJDNnRYRUprSmp6YTJzQ1huaU0KDnfM4txPnSOpSomCUl++Ib/ehlZE4QVK
        +bqyBIdCMkwzOqVdbRpmNVUzJoFxZ5gz25tQFLJG+uUpzPnFN5xYwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-16T07:56:19Z"
  mac: ENC[AES256_GCM,data:RodRJXqV2Hr48Fb50wO6S5PWfc2Uedld+ZITGJMlCf/fv52DfN0UZYDYiUAXkDGftIXR8DFZcNA+R/U1MgFpMPvmFGPn99Z4uOcd3YpPuGCDpqppPVpVkxdQxq3lsLNbIPt8xwBwRUVgKF/UupefmC+F+MjQbv1/rzSYBC7m7sg=,iv:rc5ElXyz6EF3ajLt9mpoAMuj4pcd8YHd0XRvGUZuD0U=,tag:eyHOM2dPqnulmFxeleb3fw==,type:str]
  pgp:
    - created_at: "2026-05-16T07:51:20Z"
      enc: |-
        -----BEGIN PGP MESSAGE-----

        hQIMA7McDQbiwetaARAAu0UkMQSCRbLSGe3Cnlwe/zJtuy1/2FHMsapq5EcKubx6
        QP5PZky/b+fTT9zHO//QhBk8xd21znHAos4FBtK98QUmGJCPc9BsTWVtpbemFhRA
        0/mtC+M2f6PvxqkDobrvj9S+iqPTB+qXQWwNr4eNrOjAjTkS2r6tZpp+aDnx2Tlq
        Y5qMz6eY2bqftCWWwQsp5Udn3eVw+g2uaM+RgTx7v0IWKuxUjASjMAcYcE0zburd
        auCPuioTxaLyeeRlsE3wdbFDfPN79m7PxZ+/O8KEXqtHNft8k21gjF9Q5ZzvboHV
        IMODf4q3gK4XsjzBxTBsgjYznCUYnHAUhCRfU1gN3z/VXMDk+iEirlHewK7kn7C4
        7yIJYLKZMhc5mGTX9biFX32VKdLtNVd4Mxi78UwKj/PR0hVAVTVwFrxDfUS6n9dE
        lF1u8dEaWLiqDiZHRxPNPwXlNoBzTFswFS+ObFkNG+N7fBfJ0pqxdOkvPxG3oAzS
        hHba3ysRVsvfw+P9UTyBBNiBM/nZpD9XKuHk1Tjnk6oLA1U3n1SUytqsEMpiv5QV
        O9LF5AtnkQ8Kc4962ayuVKzV2I+mGtFqcb9tSIVmXvR3BM35E7XD4IksnwyCiBxD
        P8g6zgL12PCubkZQ4QIstgXWpv1JkuhcG8gGn71vc4ls8xK3UyOiDJ3K1GUS0D3S
        XAFrse1kYiHRqQCMAWcqVqd6xKYEYB2okw6G/3zf4d2X6pW219FGQ0/uX36lc+T3
        MXSjZNdNbo0yos7jBMN6bE9wrcP/AinDAcA0Z8xRgremNszEPveRh2oSC4lo
        =TBKR
        -----END PGP MESSAGE-----
      fp: B31C0D06E2C1EB5A
  unencrypted_suffix: _unencrypted
  mac_only_encrypted: true
  version: 3.11.0
